$TOP/core/milano/rtl/milano_pkg.sv
$TOP/core/milano/rtl/fecth_reg.sv
$TOP/core/milano/rtl/if_id_reg.sv
$TOP/core/milano/rtl/decoder.sv
$TOP/core/milano/rtl/id_ex_reg.sv
$TOP/core/milano/rtl/reg_file.sv
$TOP/core/milano/rtl/alu.sv
$TOP/core/milano/rtl/if_stage.sv
$TOP/core/milano/rtl/id_stage.sv
$TOP/core/milano/rtl/ex_stage.sv
$TOP/core/milano/rtl/milano.sv
